### ISSUE TITLE
Travis CI!

### ISSUE THREAD

**Issue by sharplet** [robrix/Set#28]
- [ ] Add `.travis.yml`
- [ ] Badges!

**Comment by robrix** [comment]
Yes please :+1:

**Comment by sharplet** [comment]
Ok so looks like I don't have access to add this repo on Travis. (Maybe because it's under your username rather than an organisation?) Would you mind connecting the repo? Then I'll open a PR with a `.travis.yml` and test it out.

**Comment by robrix** [comment]
I think I’ve connected it. I’m not actually 100% sure since I’ve never done this before :smile:

**Comment by sharplet** [comment]
Link to builds page: https://travis-ci.org/robrix/Set

**Comment by sharplet** [comment]
Link to PR: https://github.com/robrix/Set/pull/34
