### ISSUE TITLE
`difference` is actually `relativeComplement`

### ISSUE THREAD

**Issue by robrix** [robrix/Set#29]
The [symmetric difference](http://en.wikipedia.org/wiki/Symmetric_difference) of sets `a` and `b` is `(a + b) - (a & b)` (the union minus the intersection). `difference()` is actually doing the equivalent of `a - b` which is the [relative complement](http://en.wikipedia.org/wiki/Complement_(set_theory)) of `b` in `a`.

We should rename `difference` to `complement` or `relativeComplement` and implement a real symmetric difference method.

cf #4.

**Comment by sharplet** [comment]
Voting for `complement`, as opposed to `relativeComplement`, which I think implies it's the relative kind due to the types involved. We don't have a useful idea of a "universe" to absolutely complement with respect to.

**Comment by robrix** [comment]
That’s my thinking as well :+1:
