### ISSUE TITLE
Multiset's isEmpty returns false even if count == 0

### ISSUE THREAD

**Issue by madbat** [robrix/Set#53]
Declared (and desired) behavior for isEmpty – True iff `count` is 0 – differs from actual behavior:

![schermata 2015-06-02 alle 18 33 59](https://cloud.githubusercontent.com/assets/325137/7941198/e9876dae-0955-11e5-93c4-9e18c00d9ff6.png)

**Comment by robrix** [comment]
Good catch, thanks :+1:
